### ISSUE TITLE
Can't run LDK v0.4.11 with CreateReactApp v4 

### ISSUE THREAD

**Issue by Janaka-Steph** [vulpemventures/ldk#115]
Can't run LDK v0.4.11 with CreateReactApp v4 

```
./node_modules/ecpair/src/ecpair.js 80:7
Module parse failed: Unexpected token (80:7)
File was processed with these loaders:
 * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| 
|   class ECPair {
>     __D;
|     __Q;
|     compressed;

```

**Comment by tiero** [comment]
This comes from breaking change in BitcoinJS that drops ECPair from inside the library.


Shall we remove ECPair entirely and let clients import it? Like we do with Marina? @louisinger

**Comment by louisinger** [comment]
> This comes from breaking change in BitcoinJS that drops ECPair from inside the library.
> Shall we remove ECPair entirely and let clients import it? Like we do with Marina? @louisinger

We can't totally remove it from LDK because lot of classes and functions depends on `ECPairFactory`. The changes introduced by new bitcoinjs-lib is the "injected ecc lib" (handled by new parameter in IdentityInterface constructor). 

It looks like the error u mentionned @Janaka-Steph  is a babel-loader error (not able to parse the "__" token probably introduced by the new ecpair version) -> I think it will fail even if we import `ecpair` directly in the project. https://github.com/bitcoinjs/ecpair/issues/2 looks related to the error u get (I think babel-loader is missing something to parse correctly the ecpair.js file)

**Comment by tiero** [comment]
FYI only solution is to upgrade to webpack v5 and do the following tweak to the config 

- https://github.com/bitcoinjs/tiny-secp256k1/blob/v2.2.1/examples/react-app/webpack.config.js#L39-L45
- https://github.com/bitcoinjs/tiny-secp256k1/blob/v2.2.1/examples/react-app/webpack.config.js#L31-L33
